### ISSUE TITLE
Add image of the UI

### ISSUE THREAD

**Issue by amilajack** [electrode-io/electrode-webpack-reporter#1]
I'm assuming that this is a html UI for webpack. Would be great if you could post a screenshot of the UI. Thanks!

**Comment by jchip** [comment]
It's just a quick hack to convert the terminal output to HTML for now, a more fancy one is under consideration.

![webpack-reporter](https://cloud.githubusercontent.com/assets/5876741/18807820/1aae3b22-8206-11e6-95b4-97819d9deb6d.png)
